"""baseline schema

Revision ID: 65a912bb5140
Revises: 
Create Date: 2026-06-13 10:13:27.504401

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65a912bb5140'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crm_company',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('city', sa.String(length=80), nullable=True),
    sa.Column('state', sa.String(length=20), nullable=True),
    sa.Column('org_type', sa.String(length=40), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('tags', sa.String(length=255), nullable=True),
    sa.Column('fiscal_year_end', sa.String(length=40), nullable=True),
    sa.Column('revenue', sa.Float(), nullable=True),
    sa.Column('employees', sa.Integer(), nullable=True),
    sa.Column('billing_cycle', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('crm_email_template',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('subject', sa.String(length=200), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('crm_segment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('state', sa.String(length=20), nullable=True),
    sa.Column('org_type', sa.String(length=40), nullable=True),
    sa.Column('tag', sa.String(length=80), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('crm_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('planting_guide',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('zone', sa.String(length=10), nullable=True),
    sa.Column('seed_indoor_start_doy', sa.Integer(), nullable=True),
    sa.Column('direct_sow_start_doy', sa.Integer(), nullable=True),
    sa.Column('direct_sow_end_doy', sa.Integer(), nullable=True),
    sa.Column('transplant_start_doy', sa.Integer(), nullable=True),
    sa.Column('transplant_end_doy', sa.Integer(), nullable=True),
    sa.Column('days_to_harvest_min', sa.Integer(), nullable=True),
    sa.Column('days_to_harvest_max', sa.Integer(), nullable=True),
    sa.Column('succession_interval_days', sa.Integer(), nullable=True),
    sa.Column('frost_sensitive', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('companion_plants', sa.String(length=300), nullable=True),
    sa.Column('avoid_near', sa.String(length=300), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pricing_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('global_multiplier', sa.Float(), nullable=True),
    sa.Column('supply_weight', sa.Float(), nullable=True),
    sa.Column('velocity_weight', sa.Float(), nullable=True),
    sa.Column('time_decay_weight', sa.Float(), nullable=True),
    sa.Column('floor_pct', sa.Float(), nullable=True),
    sa.Column('ceiling_pct', sa.Float(), nullable=True),
    sa.Column('commission_enabled', sa.Boolean(), nullable=True),
    sa.Column('delivery_fees_enabled', sa.Boolean(), nullable=True),
    sa.Column('per_mile_enabled', sa.Boolean(), nullable=True),
    sa.Column('free_delivery_enabled', sa.Boolean(), nullable=True),
    sa.Column('platform_commission_pct', sa.Float(), nullable=True),
    sa.Column('delivery_fee_flat', sa.Float(), nullable=True),
    sa.Column('delivery_fee_per_mile', sa.Float(), nullable=True),
    sa.Column('delivery_fee_free_threshold', sa.Float(), nullable=True),
    sa.Column('doordash_enabled', sa.Boolean(), nullable=True),
    sa.Column('doordash_subsidy_pct', sa.Float(), nullable=True),
    sa.Column('doordash_max_subsidy', sa.Float(), nullable=True),
    sa.Column('garden_pro_enabled', sa.Boolean(), nullable=True),
    sa.Column('garden_pro_trial_days', sa.Integer(), nullable=True),
    sa.Column('garden_pro_monthly_cents', sa.Integer(), nullable=True),
    sa.Column('garden_pro_yearly_cents', sa.Integer(), nullable=True),
    sa.Column('garden_dues_fee_percent', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('processed_stripe_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.String(length=255), nullable=False),
    sa.Column('event_type', sa.String(length=80), nullable=True),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('processed_stripe_event', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_processed_stripe_event_event_id'), ['event_id'], unique=True)

    op.create_table('site_email_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('header_color', sa.String(length=7), nullable=True),
    sa.Column('tagline', sa.String(length=200), nullable=True),
    sa.Column('footer_text', sa.Text(), nullable=True),
    sa.Column('from_name', sa.String(length=100), nullable=True),
    sa.Column('subject_prefix', sa.String(length=50), nullable=True),
    sa.Column('enable_order_confirmation', sa.Boolean(), nullable=True),
    sa.Column('enable_status_updates', sa.Boolean(), nullable=True),
    sa.Column('enable_messages', sa.Boolean(), nullable=True),
    sa.Column('enable_announcements', sa.Boolean(), nullable=True),
    sa.Column('enable_subscription_boxes', sa.Boolean(), nullable=True),
    sa.Column('enable_sms_order_confirmation', sa.Boolean(), nullable=True),
    sa.Column('enable_sms_status_updates', sa.Boolean(), nullable=True),
    sa.Column('enable_sms_messages', sa.Boolean(), nullable=True),
    sa.Column('enable_harvest_notifications', sa.Boolean(), nullable=True),
    sa.Column('enable_sms_harvest_notifications', sa.Boolean(), nullable=True),
    sa.Column('marketplace_enabled', sa.Boolean(), nullable=True),
    sa.Column('analytics_enabled', sa.Boolean(), nullable=True),
    sa.Column('cookie_consent_required', sa.Boolean(), nullable=True),
    sa.Column('analytics_retention_days', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('role', sa.String(length=10), nullable=True),
    sa.Column('display_name', sa.String(length=100), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=50), nullable=True),
    sa.Column('zip_code', sa.String(length=20), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('profile_image', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_active_user', sa.Boolean(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('gardening_story', sa.Text(), nullable=True),
    sa.Column('years_gardening', sa.Integer(), nullable=True),
    sa.Column('gallery_image_1', sa.String(length=255), nullable=True),
    sa.Column('gallery_image_2', sa.String(length=255), nullable=True),
    sa.Column('gallery_image_3', sa.String(length=255), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('sms_opt_in', sa.Boolean(), nullable=True),
    sa.Column('device_token', sa.String(length=255), nullable=True),
    sa.Column('device_platform', sa.String(length=10), nullable=True),
    sa.Column('token_version', sa.Integer(), nullable=True),
    sa.Column('email_order_updates', sa.Boolean(), nullable=True),
    sa.Column('email_messages', sa.Boolean(), nullable=True),
    sa.Column('email_harvest_alerts', sa.Boolean(), nullable=True),
    sa.Column('email_garden_announcements', sa.Boolean(), nullable=True),
    sa.Column('stripe_customer_id', sa.String(length=255), nullable=True),
    sa.Column('stripe_connect_account_id', sa.String(length=255), nullable=True),
    sa.Column('stripe_onboarding_complete', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('analytics_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('page_url', sa.String(length=500), nullable=True),
    sa.Column('referrer', sa.String(length=500), nullable=True),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('device_type', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('analytics_event', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_analytics_event_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_analytics_event_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_analytics_event_session_id'), ['session_id'], unique=False)
        batch_op.create_index('ix_analytics_type_created', ['event_type', 'created_at'], unique=False)

    op.create_table('community_garden',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('slug', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('address', sa.String(length=300), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=2), nullable=True),
    sa.Column('zip_code', sa.String(length=10), nullable=True),
    sa.Column('photo_url', sa.String(length=300), nullable=True),
    sa.Column('total_plots', sa.Integer(), nullable=True),
    sa.Column('plot_fee_annual', sa.Float(), nullable=True),
    sa.Column('operating_model', sa.String(length=20), nullable=True),
    sa.Column('season_start', sa.Date(), nullable=True),
    sa.Column('season_end', sa.Date(), nullable=True),
    sa.Column('rules', sa.Text(), nullable=True),
    sa.Column('contact_email', sa.String(length=150), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('max_checkouts_per_member', sa.Integer(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('weather_alerts_enabled', sa.Boolean(), nullable=True),
    sa.Column('grid_rows', sa.Integer(), nullable=True),
    sa.Column('grid_cols', sa.Integer(), nullable=True),
    sa.Column('organizer_id', sa.Integer(), nullable=False),
    sa.Column('subscription_status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organizer_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('crm_campaign',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('subject', sa.String(length=200), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('audience_desc', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['crm_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('crm_contact',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('image', sa.String(length=255), nullable=True),
    sa.Column('email_opt_out', sa.Boolean(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['crm_company.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('harvest_interest',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('notify_email', sa.Boolean(), nullable=True),
    sa.Column('notify_sms', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'category', name='uq_harvest_interest')
    )
    op.create_table('listing',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('seller_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('vegetable_type', sa.String(length=50), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('base_price', sa.Float(), nullable=True),
    sa.Column('initial_quantity', sa.Integer(), nullable=True),
    sa.Column('price_floor', sa.Float(), nullable=True),
    sa.Column('price_ceiling', sa.Float(), nullable=True),
    sa.Column('smart_pricing_enabled', sa.Boolean(), nullable=True),
    sa.Column('unit', sa.String(length=30), nullable=True),
    sa.Column('quantity_available', sa.Integer(), nullable=True),
    sa.Column('image_filename', sa.String(length=255), nullable=True),
    sa.Column('image_filename_2', sa.String(length=255), nullable=True),
    sa.Column('image_filename_3', sa.String(length=255), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('pickup_address', sa.String(length=255), nullable=True),
    sa.Column('pickup_city', sa.String(length=100), nullable=True),
    sa.Column('pickup_state', sa.String(length=50), nullable=True),
    sa.Column('pickup_zip', sa.String(length=20), nullable=True),
    sa.Column('pickup_latitude', sa.Float(), nullable=True),
    sa.Column('pickup_longitude', sa.Float(), nullable=True),
    sa.Column('delivery_available', sa.Boolean(), nullable=True),
    sa.Column('delivery_radius_miles', sa.Float(), nullable=True),
    sa.Column('pickup_instructions', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['seller_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('neighborhood_group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('neighborhood', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=2), nullable=True),
    sa.Column('zip_code', sa.String(length=10), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('cover_photo_url', sa.String(length=300), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('pending_checkout',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payment_intent_id', sa.String(length=255), nullable=False),
    sa.Column('buyer_id', sa.Integer(), nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=False),
    sa.Column('fulfilled', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['buyer_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pending_checkout', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pending_checkout_payment_intent_id'), ['payment_intent_id'], unique=True)

    op.create_table('promo_code',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('discount_type', sa.String(length=20), nullable=False),
    sa.Column('discount_value', sa.Float(), nullable=False),
    sa.Column('scope', sa.String(length=20), nullable=True),
    sa.Column('max_uses', sa.Integer(), nullable=True),
    sa.Column('current_uses', sa.Integer(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('seller_payout',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('seller_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('period_start', sa.Date(), nullable=True),
    sa.Column('period_end', sa.Date(), nullable=True),
    sa.Column('order_ids', sa.Text(), nullable=True),
    sa.Column('payout_reference', sa.String(length=255), nullable=True),
    sa.Column('stripe_transfer_id', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['seller_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subscription_plan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('seller_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('frequency', sa.String(length=20), nullable=True),
    sa.Column('fulfillment_day', sa.String(length=10), nullable=True),
    sa.Column('season_start', sa.Date(), nullable=True),
    sa.Column('season_end', sa.Date(), nullable=True),
    sa.Column('max_subscribers', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('photo_url', sa.String(length=300), nullable=True),
    sa.Column('box_size', sa.String(length=20), nullable=True),
    sa.Column('includes_delivery', sa.Boolean(), nullable=True),
    sa.Column('delivery_radius_miles', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['seller_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('box_preview',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('week_of', sa.Date(), nullable=False),
    sa.Column('items_description', sa.Text(), nullable=True),
    sa.Column('photo_url', sa.String(length=300), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['subscription_plan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cart_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('buyer_id', sa.Integer(), nullable=False),
    sa.Column('listing_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('added_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['buyer_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['listing_id'], ['listing.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('buyer_id', 'listing_id')
    )
    op.create_table('crm_campaign_recipient',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['crm_campaign.id'], ),
    sa.ForeignKeyConstraint(['contact_id'], ['crm_contact.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('crm_content_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('scheduled_date', sa.Date(), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('campaign_id', sa.Integer(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['crm_campaign.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['crm_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('crm_deal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('stage', sa.String(length=50), nullable=True),
    sa.Column('contact_id', sa.Integer(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('close_date', sa.Date(), nullable=True),
    sa.Column('closed_reason', sa.String(length=200), nullable=True),
    sa.Column('last_activity_at', sa.DateTime(), nullable=True),
    sa.Column('funding_source', sa.String(length=120), nullable=True),
    sa.Column('grant_status', sa.String(length=40), nullable=True),
    sa.Column('budget_decision_date', sa.Date(), nullable=True),
    sa.Column('rfp_due_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['crm_company.id'], ),
    sa.ForeignKeyConstraint(['contact_id'], ['crm_contact.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['crm_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('garden_announcement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('garden_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=True),
    sa.Column('pinned', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['garden_id'], ['community_garden.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('garden_dues_record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('garden_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('season_year', sa.Integer(), nullable=False),
    sa.Column('amount_due', sa.Float(), nullable=False),
    sa.Column('amount_paid', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('payment_method', sa.String(length=30), nullable=True),
    sa.Column('payment_date', sa.Date(), nullable=True),
    sa.Column('payment_note', sa.Text(), nullable=True),
    sa.Column('stripe_payment_intent_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['garden_id'], ['community_garden.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('garden_id', 'user_id', 'season_year')
    )
    op.create_table('garden_email_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('garden_id', sa.Integer(), nullable=False),
    sa.Column('sender_name', sa.String(length=100), nullable=True),
    sa.Column('subject_prefix', sa.String(length=50), nullable=True),
    sa.Column('closing_text', sa.String(length=300), nullable=True),
    sa.Column('accent_color', sa.String(length=7), nullable=True),
    sa.Column('sms_enabled', sa.Boolean(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['garden_id'], ['community_garden.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('garden_id')
    )
    op.create_table('garden_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('garden_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('event_type', sa.String(length=30), nullable=True),
    sa.Column('event_date', sa.DateTime(), nullable=False),
    sa.Column('duration_hours', sa.Float(), nullable=True),
    sa.Column('max_volunteers', sa.Integer(), nullable=True),
    sa.Column('recurring', sa.String(length=20), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['garden_id'], ['community_garden.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('garden_expense',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('garden_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('expense_date', sa.Date(), nullable=False),
    sa.Column('paid_by', sa.String(length=100), nullable=True),
    sa.Column('receipt_url', sa.String(length=300), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['garden_id'], ['community_garden.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('garden_knowledge_article',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('garden_id', sa.Integer(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('pinned', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['garden_id'], ['community_garden.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('garden_layout_draft',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('garden_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('grid_rows', sa.Integer(), nullable=True),
    sa.Column('grid_cols', sa.Integer(), nullable=True),
    sa.Column('layout_data', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['garden_id'], ['community_garden.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('garden_membership',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('garden_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=30), nullable=True),
    sa.Column('joined_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['garden_id'], ['community_garden.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('garden_id', 'user_id')
    )
    op.create_table('garden_message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('garden_id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('recipient_id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=200), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['garden_id'], ['community_garden.id'], ),
    sa.ForeignKeyConstraint(['recipient_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('garden_photo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('garden_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('photo_url', sa.String(length=300), nullable=False),
    sa.Column('caption', sa.String(length=500), nullable=True),
    sa.Column('category', sa.String(length=30), nullable=True),
    sa.Column('likes_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['garden_id'], ['community_garden.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('garden_plot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('garden_id', sa.Integer(), nullable=False),
    sa.Column('plot_number', sa.String(length=20), nullable=False),
    sa.Column('size', sa.String(length=30), nullable=True),
    sa.Column('location_notes', sa.String(length=200), nullable=True),
    sa.Column('grid_row', sa.Integer(), nullable=True),
    sa.Column('grid_col', sa.Integer(), nullable=True),
    sa.Column('soil_type', sa.String(length=30), nullable=True),
    sa.Column('sun_exposure', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('assigned_to_id', sa.Integer(), nullable=True),
    sa.Column('assigned_date', sa.Date(), nullable=True),
    sa.Column('renewal_date', sa.Date(), nullable=True),
    sa.Column('reserved_by_id', sa.Integer(), nullable=True),
    sa.Column('reserved_at', sa.DateTime(), nullable=True),
    sa.Column('custom_name', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['garden_id'], ['community_garden.id'], ),
    sa.ForeignKeyConstraint(['reserved_by_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('garden_subscription',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('garden_id', sa.Integer(), nullable=False),
    sa.Column('billing_cycle', sa.String(length=10), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('trial_start', sa.DateTime(), nullable=True),
    sa.Column('trial_end', sa.DateTime(), nullable=True),
    sa.Column('current_period_start', sa.DateTime(), nullable=True),
    sa.Column('current_period_end', sa.DateTime(), nullable=True),
    sa.Column('cancel_at_period_end', sa.Boolean(), nullable=True),
    sa.Column('payment_reference', sa.String(length=255), nullable=True),
    sa.Column('stripe_subscription_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['garden_id'], ['community_garden.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('garden_id')
    )
    op.create_table('garden_waitlist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('garden_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('requested_at', sa.DateTime(), nullable=True),
    sa.Column('plot_size_pref', sa.String(length=30), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['garden_id'], ['community_garden.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('garden_weather_alert',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('garden_id', sa.Integer(), nullable=False),
    sa.Column('alert_type', sa.String(length=30), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('active_from', sa.DateTime(), nullable=True),
    sa.Column('active_until', sa.DateTime(), nullable=True),
    sa.Column('auto_generated', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['garden_id'], ['community_garden.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('group_membership',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.Column('joined_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['neighborhood_group.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_id', 'user_id')
    )
    op.create_table('group_post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('post_type', sa.String(length=20), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('photo_url', sa.String(length=300), nullable=True),
    sa.Column('event_date', sa.DateTime(), nullable=True),
    sa.Column('event_location', sa.String(length=200), nullable=True),
    sa.Column('pinned', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['neighborhood_group.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('harvest_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('garden_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('variety', sa.String(length=100), nullable=True),
    sa.Column('quantity_lbs', sa.Float(), nullable=True),
    sa.Column('harvest_date', sa.Date(), nullable=False),
    sa.Column('destination', sa.String(length=30), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['garden_id'], ['community_garden.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('thread_id', sa.String(length=64), nullable=True),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('recipient_id', sa.Integer(), nullable=False),
    sa.Column('listing_id', sa.Integer(), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['listing_id'], ['listing.id'], ),
    sa.ForeignKeyConstraint(['recipient_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_message_thread_id'), ['thread_id'], unique=False)

    op.create_table('notification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('link', sa.String(length=300), nullable=True),
    sa.Column('garden_id', sa.Integer(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['garden_id'], ['community_garden.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('buyer_id', sa.Integer(), nullable=False),
    sa.Column('seller_id', sa.Integer(), nullable=False),
    sa.Column('total_price', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('fulfillment_method', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('payment_reference', sa.String(length=255), nullable=True),
    sa.Column('payment_status', sa.String(length=50), nullable=True),
    sa.Column('stripe_payment_intent_id', sa.String(length=255), nullable=True),
    sa.Column('refund_status', sa.String(length=20), nullable=True),
    sa.Column('refund_amount', sa.Float(), nullable=True),
    sa.Column('discount_amount', sa.Float(), nullable=True),
    sa.Column('promo_code_id', sa.Integer(), nullable=True),
    sa.Column('subtotal', sa.Float(), nullable=True),
    sa.Column('delivery_fee', sa.Float(), nullable=True),
    sa.Column('platform_commission', sa.Float(), nullable=True),
    sa.Column('commission_rate', sa.Float(), nullable=True),
    sa.Column('seller_earnings', sa.Float(), nullable=True),
    sa.Column('doordash_delivery_id', sa.String(length=255), nullable=True),
    sa.Column('doordash_tracking_url', sa.String(length=500), nullable=True),
    sa.Column('delivery_provider', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['buyer_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['promo_code_id'], ['promo_code.id'], ),
    sa.ForeignKeyConstraint(['seller_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('photo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('garden_id', sa.Integer(), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['garden_id'], ['community_garden.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('seller_planting',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('seller_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('variety', sa.String(length=100), nullable=True),
    sa.Column('planted_date', sa.Date(), nullable=False),
    sa.Column('estimated_harvest_start', sa.Date(), nullable=True),
    sa.Column('estimated_harvest_end', sa.Date(), nullable=True),
    sa.Column('quantity_estimate', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('allow_preorder', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('linked_listing_id', sa.Integer(), nullable=True),
    sa.Column('auto_list_on_harvest', sa.Boolean(), nullable=True),
    sa.Column('weight_lbs', sa.Float(), nullable=True),
    sa.Column('sale_price', sa.Float(), nullable=True),
    sa.Column('price_unit', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['linked_listing_id'], ['listing.id'], ),
    sa.ForeignKeyConstraint(['seller_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shared_resource',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('garden_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=30), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('condition', sa.String(length=20), nullable=True),
    sa.Column('checked_out_to_id', sa.Integer(), nullable=True),
    sa.Column('checked_out_at', sa.DateTime(), nullable=True),
    sa.Column('checkout_duration_days', sa.Integer(), nullable=True),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('qr_code_token', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['checked_out_to_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['garden_id'], ['community_garden.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subscription',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('buyer_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('dietary_notes', sa.Text(), nullable=True),
    sa.Column('substitution_pref', sa.String(length=30), nullable=True),
    sa.Column('delivery_preference', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('paused_at', sa.DateTime(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['buyer_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['subscription_plan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('volunteer_shift',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('garden_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('shift_date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('max_volunteers', sa.Integer(), nullable=True),
    sa.Column('recurring', sa.String(length=20), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['garden_id'], ['community_garden.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('crm_activity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=True),
    sa.Column('description', sa.String(length=400), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('contact_id', sa.Integer(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('deal_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['crm_company.id'], ),
    sa.ForeignKeyConstraint(['contact_id'], ['crm_contact.id'], ),
    sa.ForeignKeyConstraint(['deal_id'], ['crm_deal.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['crm_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('crm_deal_contact',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deal_id', sa.Integer(), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=40), nullable=True),
    sa.ForeignKeyConstraint(['contact_id'], ['crm_contact.id'], ),
    sa.ForeignKeyConstraint(['deal_id'], ['crm_deal.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('crm_note',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('deal_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['crm_company.id'], ),
    sa.ForeignKeyConstraint(['contact_id'], ['crm_contact.id'], ),
    sa.ForeignKeyConstraint(['deal_id'], ['crm_deal.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('crm_task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('done', sa.Boolean(), nullable=True),
    sa.Column('priority', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('contact_id', sa.Integer(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('deal_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['crm_company.id'], ),
    sa.ForeignKeyConstraint(['contact_id'], ['crm_contact.id'], ),
    sa.ForeignKeyConstraint(['deal_id'], ['crm_deal.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('event_rsvp',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['garden_event.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'user_id')
    )
    op.create_table('garden_photo_comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('photo_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['photo_id'], ['garden_photo.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('garden_photo_like',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('photo_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['photo_id'], ['garden_photo.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('photo_id', 'user_id')
    )
    op.create_table('group_post_comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['group_post.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('listing_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('unit_price', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['listing_id'], ['listing.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plot_assignment_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plot_id', sa.Integer(), nullable=False),
    sa.Column('garden_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('season_year', sa.Integer(), nullable=False),
    sa.Column('assigned_date', sa.Date(), nullable=True),
    sa.Column('released_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['garden_id'], ['community_garden.id'], ),
    sa.ForeignKeyConstraint(['plot_id'], ['garden_plot.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('promo_code_usage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('promo_code_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('garden_subscription_id', sa.Integer(), nullable=True),
    sa.Column('discount_applied', sa.Float(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['garden_subscription_id'], ['garden_subscription.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.ForeignKeyConstraint(['promo_code_id'], ['promo_code.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('refund',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('garden_subscription_id', sa.Integer(), nullable=True),
    sa.Column('refund_type', sa.String(length=20), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('stripe_refund_id', sa.String(length=255), nullable=True),
    sa.Column('stripe_reversal_id', sa.String(length=255), nullable=True),
    sa.Column('initiated_by_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['garden_subscription_id'], ['garden_subscription.id'], ),
    sa.ForeignKeyConstraint(['initiated_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('resource_checkout_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('garden_id', sa.Integer(), nullable=False),
    sa.Column('checked_out_at', sa.DateTime(), nullable=True),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('returned_at', sa.DateTime(), nullable=True),
    sa.Column('duration_days', sa.Integer(), nullable=True),
    sa.Column('condition_at_checkout', sa.String(length=20), nullable=True),
    sa.Column('condition_at_return', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['garden_id'], ['community_garden.id'], ),
    sa.ForeignKeyConstraint(['resource_id'], ['shared_resource.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('review',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reviewer_id', sa.Integer(), nullable=False),
    sa.Column('seller_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.ForeignKeyConstraint(['reviewer_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['seller_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_id')
    )
    op.create_table('shift_signup',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shift_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('hours_logged', sa.Float(), nullable=True),
    sa.Column('checked_in_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['shift_id'], ['volunteer_shift.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shift_id', 'user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shift_signup')
    op.drop_table('review')
    op.drop_table('resource_checkout_log')
    op.drop_table('refund')
    op.drop_table('promo_code_usage')
    op.drop_table('plot_assignment_history')
    op.drop_table('order_item')
    op.drop_table('group_post_comment')
    op.drop_table('garden_photo_like')
    op.drop_table('garden_photo_comment')
    op.drop_table('event_rsvp')
    op.drop_table('crm_task')
    op.drop_table('crm_note')
    op.drop_table('crm_deal_contact')
    op.drop_table('crm_activity')
    op.drop_table('volunteer_shift')
    op.drop_table('subscription')
    op.drop_table('shared_resource')
    op.drop_table('seller_planting')
    op.drop_table('photo')
    op.drop_table('order')
    op.drop_table('notification')
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_message_thread_id'))

    op.drop_table('message')
    op.drop_table('harvest_log')
    op.drop_table('group_post')
    op.drop_table('group_membership')
    op.drop_table('garden_weather_alert')
    op.drop_table('garden_waitlist')
    op.drop_table('garden_subscription')
    op.drop_table('garden_plot')
    op.drop_table('garden_photo')
    op.drop_table('garden_message')
    op.drop_table('garden_membership')
    op.drop_table('garden_layout_draft')
    op.drop_table('garden_knowledge_article')
    op.drop_table('garden_expense')
    op.drop_table('garden_event')
    op.drop_table('garden_email_config')
    op.drop_table('garden_dues_record')
    op.drop_table('garden_announcement')
    op.drop_table('crm_deal')
    op.drop_table('crm_content_item')
    op.drop_table('crm_campaign_recipient')
    op.drop_table('cart_item')
    op.drop_table('box_preview')
    op.drop_table('subscription_plan')
    op.drop_table('seller_payout')
    op.drop_table('promo_code')
    with op.batch_alter_table('pending_checkout', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pending_checkout_payment_intent_id'))

    op.drop_table('pending_checkout')
    op.drop_table('neighborhood_group')
    op.drop_table('listing')
    op.drop_table('harvest_interest')
    op.drop_table('crm_contact')
    op.drop_table('crm_campaign')
    op.drop_table('community_garden')
    with op.batch_alter_table('analytics_event', schema=None) as batch_op:
        batch_op.drop_index('ix_analytics_type_created')
        batch_op.drop_index(batch_op.f('ix_analytics_event_session_id'))
        batch_op.drop_index(batch_op.f('ix_analytics_event_event_type'))
        batch_op.drop_index(batch_op.f('ix_analytics_event_created_at'))

    op.drop_table('analytics_event')
    op.drop_table('user')
    op.drop_table('site_email_config')
    with op.batch_alter_table('processed_stripe_event', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_processed_stripe_event_event_id'))

    op.drop_table('processed_stripe_event')
    op.drop_table('pricing_config')
    op.drop_table('planting_guide')
    op.drop_table('crm_user')
    op.drop_table('crm_segment')
    op.drop_table('crm_email_template')
    op.drop_table('crm_company')
    # ### end Alembic commands ###
